In [37]:
import sys
from pathlib import Path
import json
from datetime import datetime, UTC

PROJECT_ROOT = Path.cwd().parents[0]  # adjust if notebook is nested deeper
sys.path.append(str(PROJECT_ROOT))

In [38]:
from src.shared.database.client import SQLModelClient
import pandas as pd

In [39]:
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.io as pio
import warnings
# Set ploting default
pio.templates.default = "plotly_dark"
px.defaults.height = 600
px.defaults.template = "plotly_dark"
px.defaults.color_continuous_scale = px.colors.sequential.Bluyl_r
px.defaults.color_discrete_sequence = px.colors.sequential.Bluyl_r


plotly_config = {
  "staticPlot": True,
#   "scrollZoom": True,
  "displayModeBar": False,
  "editable": True,
}


# np.random.seed (21)
pd.set_option ("display.max_rows", 20)
pd.set_option ("display.max_columns", 15)
pd.options.plotting.backend = "plotly"

# mute warnings
warnings.filterwarnings ("ignore")

In [40]:
!pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in /Users/kunmi/Projects/workspace/data_engineering/asset_monitoring_system/venv/lib/python3.13/site-packages (2.9.11)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [41]:
database_client = SQLModelClient(database_url="postgresql://dev_user_1:dev_user_1_password@localhost:5432/investment_db")

In [42]:
# Asset List
with database_client as db:
  res = db.execute(
    f"""
    SELECT  *
    FROM staging.account t1
    WHERE CAST(created_timestamp AS DATE) = '20260308'
    ORDER BY created_timestamp DESC
  """
  )
  res = res.fetchall()
  
df_account = pd.DataFrame(res)

In [43]:
df_account.head(3)

,id,data_timestamp,external_id,cash_in_pies,cash_available_to_trade,cash_reserved_for_orders,broker,currency,total_value,investments_total_cost,investments_realized_pnl,investments_unrealized_pnl,business_key,created_timestamp,updated_timestamp
0,50963ef9-dab8-42f1-b34c-349b30d99fe0,2026-03-08 23:40:34.525659+00:00,21641310,8.83,29.55,0.0,Trading 212,EUR,5789.98,5505.11,101.14,249.06,"21641310_""EUR""_2026-03-08 23:40:34.525659+00",2026-03-08 23:40:38.183195+00:00,None
1,79f4563d-7010-4739-bd24-633eb6fa8cfc,2026-03-08 23:40:27.730832+00:00,21641310,8.83,29.55,0.0,Trading 212,EUR,5790.12,5505.11,101.14,249.20,"21641310_""EUR""_2026-03-08 23:40:27.730832+00",2026-03-08 23:40:28.969578+00:00,None
2,26042cf7-9cd9-4662-ae24-8bb52d01a33c,2026-03-08 23:06:41.026018+00:00,21641310,8.83,29.55,0.0,Trading 212,EUR,5789.17,5505.11,101.14,248.25,"21641310_""EUR""_2026-03-08 23:06:41.026018+00",2026-03-08 23:40:28.930955+00:00,None

In [44]:
fig = px.line (
  df_account,
  "data_timestamp",
  "cash_in_pies",
  title="cash_in_pies"
#   color_discrete_sequence="Tealgrn_r",
)

fig.update_layout (
  height=500,
)

In [45]:
fig = px.line (
  df_account,
  "data_timestamp",
  "total_value",
  title="total_value"
#   color_discrete_sequence="Tealgrn_r",
)

fig.update_layout (
  height=500,
)

In [46]:
fig = px.line (
  df_account,
  "data_timestamp",
  "investments_total_cost",
  title="investments_total_cost"
#   color_discrete_sequence="Tealgrn_r",
)

fig.update_layout (
  height=500,
)

In [47]:
fig = px.line (
  df_account,
  "data_timestamp",
  "investments_unrealized_pnl",
  title="investments_unrealized_pnl"
#   color_discrete_sequence="Tealgrn_r",
)

fig.update_layout (
  height=500,
)

In [48]:
sql = """
WITH most_recent_asset AS
(
    SELECT
        ROW_NUMBER() OVER (PARTITION BY ticker ORDER BY data_timestamp DESC) AS rn,
        id
    FROM staging.asset
),
portfolio_value AS
(
    SELECT total_value
    FROM staging.account
    ORDER BY created_timestamp DESC
    LIMIT 1
)

SELECT
    a.ticker,
    a.name,
    CASE WHEN ac.ma_30d > ac.ma_50d THEN 'Bullish' ELSE 'Bearish' END AS trend,
    a.description AS asset_description,
    -- STRING_AGG(t.name, ',') AS tag_list,
    a.value,
    a.profit,
    a.price,
    a.cost,

    a.value / pv.total_value * 100 AS weight_pct,

    ac.recent_profit_high_30d,
    ac.recent_profit_low_30d,
    ac.pct_drawdown,
    ac.volatility_30d,
    ac.volatility_50d,
    ac.ma_30d,
    ac.ma_50d,
    ac.dca_bias,
    a.created_timestamp AS data_date

FROM staging.asset a
INNER JOIN most_recent_asset lm
    ON a.id = lm.id
    AND lm.rn = 1

LEFT JOIN staging.asset_computed ac
    ON a.id = ac.asset_id

CROSS JOIN portfolio_value pv

"""
# Asset List
with database_client as db:
    res = db.execute(
    sql
  )
    res = res.fetchall()


df = pd.DataFrame(res)

In [49]:
df.columns

Index(['ticker', 'name', 'trend', 'asset_description', 'value', 'profit',
       'price', 'cost', 'weight_pct', 'recent_profit_high_30d',
       'recent_profit_low_30d', 'pct_drawdown', 'volatility_30d',
       'volatility_50d', 'ma_30d', 'ma_50d', 'dca_bias', 'data_date'],
      dtype='str')

In [50]:
df.sort_values(by="weight_pct", ascending=False)

,ticker,name,trend,asset_description,value,profit,price,...,pct_drawdown,volatility_30d,volatility_50d,ma_30d,ma_50d,dca_bias,data_date
54,VUSAl,Vanguard S&P 500 (Dist),Bullish,Vanguard S&P 500 (Dist),556.11,12.64,95.4001,...,-0.005348,0.000895,0.000908,557.905667,557.2874,0.023258,2026-03-13 16:28:52.771103+00:00
55,VWRPl,Vanguard FTSE All-World (Acc),Bullish,Vanguard FTSE All-World (Acc),364.68,8.03,126.5980,...,-0.008267,0.001214,0.001177,366.661667,366.1582,0.022515,2026-03-13 16:28:52.802755+00:00
15,EQQQl,Invesco EQQQ Nasdaq-100 (Dist),Bullish,Invesco EQQQ Nasdaq-100 (Dist),326.12,-0.28,45090.0030,...,-0.007124,0.001106,0.001048,327.759667,327.4072,-0.000858,2026-03-13 16:28:52.662859+00:00
40,SEMIl,iShares MSCI Global Semiconductors (Acc),Bullish,iShares MSCI Global Semiconductors (Acc),317.27,72.04,9.5780,...,-0.013341,0.002160,0.002053,319.396000,318.3400,0.293765,2026-03-13 16:28:52.349002+00:00
24,INTLl,WisdomTree Artificial Intelligence (Acc),Bullish,WisdomTree Artificial Intelligence (Acc),242.42,11.52,6424.9000,...,-0.013711,0.002198,0.002095,243.542333,242.8898,0.049892,2026-03-13 16:28:52.839576+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,PLTR,Palantir,Bullish,Palantir,10.72,-0.70,150.3400,...,-0.026340,0.003515,0.002802,10.881000,10.8576,-0.061296,2026-03-13 16:28:52.794508+00:00
4,ALVd,Allianz,Bullish,Allianz,8.88,-0.34,354.5000,...,-0.007821,0.002336,0.001888,8.890667,8.8488,-0.036876,2026-03-13 16:28:53.079647+00:00
3,AIRp,Airbus,Bearish,Airbus,7.57,-1.41,168.3700,...,-0.014323,0.001934,0.002199,7.655000,7.6758,-0.157016,2026-03-13 16:28:52.970064+00:00
41,SFGYY,Sony Financial Group,Bearish,Sony Financial Group,6.66,0.31,4.5700,...,-0.016248,0.002319,0.001879,6.747333,6.7540,0.048819,2026-03-13 16:28:52.987932+00:00
45,SNII,Rigetti Computing,Bullish,Rigetti Computing,3.88,-3.18,16.2300,...,-0.041975,0.006864,0.005464,3.899333,3.8734,-0.450425,2026-03-13 16:28:51.928333+00:00

In [51]:
fig = px.scatter(
    df,
    x="value",
    y="profit",
    color="ticker",
    size="weight_pct",
    hover_data=['ticker', 'name'],
    color_continuous_scale=px.colors.sequential.Bluyl_r,
)

# Add horizontal line at profit = 0
fig.add_hline(
    y=0,
    line_color="red",
    line_width=1,
    line_dash="dash"
)

fig.show()

In [96]:
"""
  Get Lastest Asset data for each day grouping by the date
"""

sql = f"""
    ;WITH cte AS (
        SELECT  *
              , CAST(created_timestamp AS date) AS created_date
              , ROW_NUMBER()OVER(PARTITION BY ticker, CAST(created_timestamp AS date) ORDER BY created_timestamp DESC) AS rn
          FROM staging.asset
          WHERE created_timestamp >= CURRENT_TIMESTAMP - INTERVAL '30 days'
          ORDER BY ticker, created_timestamp ASC
      )
      SELECT
         *
         , CASE WHEN profit > 0 THEN 1 ELSE 0 END AS is_profitable
      FROM cte
      WHERE rn = 1
    """
# Asset List
with database_client as db:
    res = db.execute(
    sql
  )
    res = res.fetchall()


df = pd.DataFrame(res)

In [74]:
df.head(3)

,id,data_timestamp,external_id,ticker,name,description,broker,...,profit,fx_impact,business_key,created_timestamp,updated_timestamp,created_date,rn
0,01e1f5e0-5645-4027-a3c7-8dd5006c2404,2026-02-21 23:42:41.211035+00:00,AAPL_US_EQ,AAPL,Apple,Apple,Trading 212,...,1.18,-0.42,85069faf-f124-4702-94c2-8d8e90119b1d_AAPL_US_E...,2026-02-21 23:52:40.826473+00:00,None,2026-02-21,1
1,171efd8e-3f33-4ae6-a61b-a2b12f5567f0,2026-02-22 23:40:33.292936+00:00,AAPL_US_EQ,AAPL,Apple,Apple,Trading 212,...,1.13,-0.46,f5e0d689-b803-47ef-adc4-6c31242bb57a_AAPL_US_E...,2026-02-22 23:50:34.075286+00:00,None,2026-02-22,1
2,88cc6976-77fa-4f18-b905-322aff68ee9a,2026-02-23 23:50:32.741890+00:00,AAPL_US_EQ,AAPL,Apple,Apple,Trading 212,...,1.30,-0.43,209607d3-3e94-4f7e-aa74-848a6b4a6b8f_AAPL_US_E...,2026-02-23 23:50:39.871938+00:00,None,2026-02-23,1

In [ ]:
df.columns

df['is_profitable'] = df["profit"].apply(lambda x: 1 if x > 0 else 0)

In [75]:
df['created_timestamp'][0].date()

datetime.date(2026, 2, 21)

In [105]:
df_sharpe_profit = df[df["is_profitable"] == 1].groupby('created_date')["profit"].sum().to_dict()
# df_sharpe_loss = df[df["is_profitable"] == 0].groupby('created_date')["profit"].sum().reset_index()

In [106]:
df_sharpe_profit

{datetime.date(2026, 2, 21): 464.53000000000003,
 datetime.date(2026, 2, 22): 462.09,
 datetime.date(2026, 2, 23): 448.26,
 datetime.date(2026, 2, 24): 482.76,
 datetime.date(2026, 2, 25): 521.73,
 datetime.date(2026, 2, 26): 492.69,
 datetime.date(2026, 2, 27): 491.95,
 datetime.date(2026, 2, 28): 491.88,
 datetime.date(2026, 3, 1): 491.88,
 datetime.date(2026, 3, 2): 477.75,
 datetime.date(2026, 3, 3): 418.81,
 datetime.date(2026, 3, 4): 432.4,
 datetime.date(2026, 3, 5): 399.62,
 datetime.date(2026, 3, 6): 349.58,
 datetime.date(2026, 3, 8): 356.46999999999997,
 datetime.date(2026, 3, 9): 336.35999999999996,
 datetime.date(2026, 3, 10): 424.45,
 datetime.date(2026, 3, 11): 409.45,
 datetime.date(2026, 3, 12): 376.7,
 datetime.date(2026, 3, 13): 358.73}

In [91]:
fig = px.line(
  df_sharpe_profit,
  x="created_date",
  y="profit",
)


fig.show()

In [ ]:
fig = px.line(
  df_sharpe_loss,
  x="created_date",
  y="profit",
)


fig.show()

In [115]:
sql = """
WITH most_recent_asset AS
      (
          SELECT
              ROW_NUMBER() OVER (PARTITION BY ticker ORDER BY data_timestamp DESC) AS rn,
              id
          FROM staging.asset
      ),
      portfolio_value AS
      (
          SELECT total_value
          FROM staging.account
          ORDER BY created_timestamp DESC
          LIMIT 1
      )

      SELECT
          a.ticker,
          a.name,
          CASE WHEN ac.ma_30d > ac.ma_50d THEN 'Bullish' ELSE 'Bearish' END AS trend,
          a.description AS asset_description,
          -- STRING_AGG(t.name, ',') AS tag_list,
          a.value,
          a.profit,
          a.price,
          a.cost,

          a.value / pv.total_value * 100 AS weight_pct,

          ac.recent_profit_high_30d,
          ac.recent_profit_low_30d,
          ac.pct_drawdown,
          ac.volatility_30d,
          ac.volatility_50d,
          ac.ma_30d,
          ac.ma_50d,
          ac.dca_bias,
          a.created_timestamp AS data_date

      FROM staging.asset a
      INNER JOIN most_recent_asset lm
          ON a.id = lm.id
          AND lm.rn = 1

      LEFT JOIN staging.asset_computed ac
          ON a.id = ac.asset_id

      CROSS JOIN portfolio_value pv
    """
with database_client as client:
  res = client.execute(
      sql
  )
  res = res.fetchall()
  
df = pd.DataFrame(res)

df.head(3)
df["profitable"] = df["profit"].apply(lambda x: "profit" if x > 0 else "loss")

df = df["profitable"].value_counts().to_frame().reset_index()
# fig = go.Figure(go.Pie(
#     labels=df["profitable"],
#     values=df["count"],
#     hole=0.4,
#     # marker=dict(colors=colors, line=dict(width=0)),
#     textinfo="percent+label",
#     textfont=dict(color="#ffffff", size=10),
#     hovertemplate="%{label}: %{percent}<extra></extra>",
# ))


# fig.show()

df.to_dict()

{'profitable': {0: 'profit', 1: 'loss'}, 'count': {0: 39, 1: 20}}